### ISSUE TITLE
Refactor Master Issue

### ISSUE THREAD

**Issue by mgraber** [NYCPlanning/ceqr-app-data#7]
Refactoring recipes in [ceqr-app-data-archive](https://github.com/NYCPlanning/ceqr-app-data-archive)

### Goals
+ Reduce dependencies by doing dataloading without python, where possible
+ Clean up build code to make it more legible
+ Automatically load outputs to s3 for labs

### Recipes
- [x] atypical_roadways
- [x] ceqr_school_buildings
- [x] ctpp_censustract_centroids
- [x] ctpp_censustract_variables
- [x] ctpp_journey_to_work
- [x] dcp_areas_of_concern
- [x] dep_cats_permits
- [ ] doe_significant_utilization_changes
       Most recent data is missing necessary fields. Need to decide whether to hard-code old data or rethink output.
- [x] dot_traffic_cameras
- [x] facilities_garages
- [x] nysdec_air_monitoring_stations
- [x] nysdec_state_facility_permits
- [x] nysdec_title_v_facility_permits
- [x] nysdot_aadt
- [x] nysdot_functional_class
- [x] nysdot_traffic_counts
- [x] sca_capacity_projects
- ~[ ] sca_capital_projects~
- [x] sca_e_projections_by_boro #19
- [x] sca_e_projections_by_sd #17
- [x] tunnel_ventilation_towers

**Comment by SPTKL** [comment]
#20 documentation issue

**Comment by SPTKL** [comment]
doe_significant_utilization_changes tracked in #40  everything else is done
